Dylanmccall/add standalone windows
learningequality/kolibri-installer-gnome pull request #29
Opened 2021-03-19 00:45 UTC by dylanmccall

2021-09-01 10:54 UTC, danigm approved these changes
I've been testing and it's working for me. I've just left two nitpick comments about regular expressions that can be combined in one.

2021-09-01 10:54 UTC, danigm commented on src/kolibri_gnome/desktop_launcher/application.py
> +        elif re.match(r"^\/content\/storage\/?", url_tuple.path):
This can be simplified grouping regular expressions:
```suggestion
        elif re.match(r"^\/(?P<lang>\w+\/)?(user|logout|redirectuser)\/?", url_tuple.path):
            return True
        elif re.match(r"^\/(zipcontent|app|static|downloadcontent|content\/storage)\/?", url_tuple.path):
            return True
```

But maybe this way is clearer.

2021-09-01 10:54 UTC, danigm commented on src/kolibri_gnome/desktop_launcher/application.py
> +                return match.group("node_id")
This is something that could also be simplified using just one regular expression:
```suggestion
        pattern = r"^topics\/([ct]\/)?(?P<node_id>\w+)"
        match = re.match(pattern, fragment)
        if match:
            return match.group("node_id")
```

2021-09-01 17:48 UTC, dylanmccall commented on src/kolibri_gnome/desktop_launcher/application.py
> +        elif re.match(r"^\/content\/storage\/?", url_tuple.path):
Ah, I like it. I'd started off copying these from Kolibri's urls.py, but seeing as this code is nowhere near that code, the similarity between the two doesn't really help anything. That's much better! Thank you :)

2021-09-08 17:03 UTC, danigm requested changes

2021-09-08 17:03 UTC, danigm commented on src/kolibri_gnome/desktop_launcher/application.py
> +            return True
This line is duplicated and can be removed.

```suggestion
```

2021-09-29 00:01 UTC, merged

2021-09-29 00:01 UTC, dylanmccall commented
This seems to have been working well, so I'll merge this into the master branch now.