Per channel search provider
learningequality/kolibri-installer-gnome pull request #31
Opened 2021-08-31 21:38 UTC by dylanmccall

2021-09-17 11:51 UTC, danigm requested changes
This is not building for me using flatpak with a clean clone/build, I've created a PR that solves the build problem that I've found: https://github.com/learningequality/kolibri-installer-gnome/pull/35

Besides that, this is working correctly. I've left a few comments about the code, but looks pretty good.

2021-09-17 11:51 UTC, danigm commented on src/kolibri_gnome/launcher/application.py
> +        valid_url_schemes = ("kolibri-channel", 'x-kolibri-dispatch')
This is not used now, maybe it's good to remove the variable.

2021-09-17 11:51 UTC, danigm commented on src/kolibri_gnome_search_provider/kolibri-gnome-search-provider.c
> +  // KolibriGnomeSearchProvider *self = KOLIBRI_GNOME_SEARCH_PROVIDER (gobject);
This commented line could be removed.

2021-09-17 21:38 UTC, dylanmccall commented
Thanks for the review! I pushed a change which should fix the build issue you were encountering, as well as those review comments. I'll see if I can split this up into more manageable commits as well :)

2021-09-21 09:34 UTC, danigm approved these changes
LGTM

2021-09-29 21:03 UTC, merged