Standalone scheme launch
learningequality/kolibri-installer-gnome pull request #34
Opened 2021-09-06 15:52 UTC by danigm

https://phabricator.endlessm.com/T32486

2021-09-09 20:53 UTC, dylanmccall requested changes
I like it! Good work tackling this :) One other small nitpick here is just around naming of things. I appreciate keeping the changeset simpler by not moving a dozen files around, but before merging I wonder if we should add another commit to rename desktop_launcher to just "desktop" or something, and then move `desktop_launcher/channel.py` to `launcher/application.py`?

2021-09-09 20:53 UTC, dylanmccall commented on src/kolibri_gnome/desktop_launcher/application.py
> +
Is the set of changes from this earlier commit still relevant here? The only thing passing the `?standalone` query parameter is the desktop launchers, and if we switch those to the kolibri-channel scheme then this should all be dead code.

2021-09-10 07:46 UTC, danigm commented on src/kolibri_gnome/desktop_launcher/application.py
> +
Yes, I think so, we can remove the first commit and just keep the second one with the launcher. I'll do that and I'll also add the renaming commit commented above.

2021-09-14 17:13 UTC, dylanmccall approved these changes
Thanks! I'm happy with this now, so I'll merge it into the add-standalone-windows branch.

2021-09-14 17:13 UTC, merged