WIP: Early prototype of a unified search callback
learningequality/kolibri-installer-gnome pull request #36
Opened 2021-09-23 00:49 UTC by dylanmccall

https://phabricator.endlessm.com/T32557

2021-09-28 11:50 UTC, danigm requested changes
Overall looks good to me. I've been testing and it's working as expected, but I've left some comments on the code to reuse more code.

2021-09-28 11:50 UTC, danigm commented on src/kolibri_gnome_search_provider/kolibri-gnome-search-provider.c
> +  g_auto(GStrv) filtered_item_ids = NULL;
nitpick: I don't like this variable declaration below other non variable declaration expressions, it could be better to move this above the `g_task_propagate_pointer` call.

2021-09-28 11:50 UTC, danigm commented on src/kolibri_gnome_search_provider/kolibri-gnome-search-provider.c
> +  g_auto(GStrv) filtered_item_ids = NULL;
Same as previous comment, variable declaration at the top of the scope.

2021-09-28 11:50 UTC, danigm commented on src/kolibri_gnome_search_provider/kolibri-gnome-search-provider.c
> +search_multiplexer_to_get_subsearch_result_set_invocation_async_ready_cb(GObject      *source_object,
This function is exactly the same as `search_multiplexer_to_get_item_ids_invocation_async_ready_cb`, it's not possible to use the same function instead of declaring it twice?

2021-09-28 11:50 UTC, danigm commented on src/kolibri_gnome_search_provider/kolibri-gnome-search-provider.c
>  handle_get_initial_result_set(ShellSearchProvider2   *skeleton,
This function and the following one, `handle_get_subsearch_result_set`, have exactly the same body, it could be better to define a third function with the body and common parameters and call this new one from both functions so there's no repeated code.

2021-09-28 22:12 UTC, dylanmccall commented
Thanks for the review @danigm! That helped a bunch. I took care of those details you flagged :)

2021-09-29 10:49 UTC, danigm reviewed
LGTM

2021-09-29 10:49 UTC, danigm approved these changes

2021-09-29 21:06 UTC, merged