README: Document the modules
learningequality/kolibri-installer-gnome pull request #41
Opened 2021-10-15 22:27 UTC by manuq

And talk about the optional dependency plugin for handling desktop
files.

https://phabricator.endlessm.com/T32613

2021-10-15 22:28 UTC, manuq commented
@dylanmccall feel free to reword (I'm not a native speaker) and point out things not fully understood.

2021-10-16 01:15 UTC, dylanmccall requested changes
Thank you! Great to keep this up to date. I'm realizing it would be nice to add a note about developing with GNOME Builder (we have a reference flatpak manifest in `build-aux/flatpak` so it's super easy), too.

I added a few clarifications about how certain modules work, but all's nice and clear :)

2021-10-16 01:15 UTC, dylanmccall commented on README.md
> +search results from kolibri.
To be more specific, it is possible to group search results by their respective channels by querying a channel-specific search provider object. The default search provider contains results for all channels.

2021-10-16 01:15 UTC, dylanmccall commented on README.md
> +them into kolibri-gnome arguments.
Might be good to add that it starts kolibri-gnome with a specific application ID depending on the URI, which is why we need a launcher process instead of handling these URIs in kolibri-gnome :)

2021-10-16 01:15 UTC, dylanmccall commented on README.md
> +
:+1:

2021-10-18 18:04 UTC, manuq commented on README.md
> +webview.
Ah thanks for the explanation, glad to know how eos-kolibri works with the daemon. Adding your paragraph as-is.

2021-10-19 12:06 UTC, manuq commented
> Thank you! Great to keep this up to date. I'm realizing it would be nice to add a note about developing with GNOME Builder (we have a reference flatpak manifest in `build-aux/flatpak` so it's super easy), too.

Yes! Would you like to add a section about Builder? For some reason I'm getting a loading page that loops forever right now, so I'm building with a custom flatpak manifest instead:

![Captura de pantalla de 2021-10-19 09-04-04](https://user-images.githubusercontent.com/83944/137905744-9f66684b-579e-4f20-92a1-3f03cb0b8953.png)

Would you like to also explain the recently added `libkolibri_daemon_dbus` in #42? Maybe "helper library for kolibri-daemon D-Bus interfaces"? Also if you generated it with `gdbus-codegen` it would be nice to explain that, for updating the C code in the future.

2021-10-20 19:04 UTC, manuq commented
@dylanmccall ready for review again. I attempted a section about GNOME Builder and also added a line about the new `libkolibri_daemon_dbus` helper module. I'm calling these "modules" because they are no longer all Python packages.

2021-10-21 04:00 UTC, dylanmccall approved these changes
I like it! Thanks for taking the time to document all of this.

2021-10-21 04:00 UTC, merged