T32705 autoprovision
learningequality/kolibri-installer-gnome pull request #60
Opened 2021-12-02 15:41 UTC by manuq

https://phabricator.endlessm.com/T32705

2021-12-02 22:09 UTC, dylanmccall requested changes
I have a few comments, and some things to fix. Also, may you please run `reorder-python-imports src/**/*.py` and `black` on these commits? (Sorry, keep forgetting to add that pre-commit hook here).

2021-12-02 22:09 UTC, dylanmccall commented on src/kolibri_gnome/kolibri_context.py
> +            },
We should definitely not _release_ this (and close the ticket about it) until we can create a facility without a superuser, but depending on how much trouble that looks like, I'm happy merging branch this as-is so we can test it.

```suggestion
            # FIXME: Kolibri's API requires this. We should create a facility without a superuser.
            "superuser": {
                "username": "admin",
                "password": "admin",
            },
```

2021-12-02 22:09 UTC, dylanmccall commented on src/kolibri_gnome/kolibri_daemon_manager.py
> +            # handle it in the other side to set SESSION_STATUS_ERROR.
:+1: These methods are doing too much at the moment.

2021-12-02 22:09 UTC, dylanmccall commented on src/kolibri_gnome/kolibri_daemon_manager.py
> +        logger.warning("Error reading Kolibri API response: {error}".format(error=error))
Oh, good fixes! :)

2021-12-03 00:15 UTC, dylanmccall commented on src/kolibri_gnome/kolibri_context.py
> +            },
Actually, I beat you to it. I pushed a couple commits which should solve this, and opened learningequality/kolibri#8798 :)

2021-12-03 01:45 UTC, rtibbles commented on build-aux/flatpak/modules/0001-Get-port-number-for-zeroconf-from-cherrypy.server.patch
> ++    start_with_ready_cb(port, background, ready_cb=_on_ready)
Note that this is no longer necessary with latest 0.15.0 versions - zero conf now reads the port from the chosen port if 0 is used to allow port selection.

2021-12-06 13:56 UTC, rtibbles commented on src/kolibri_gnome/kolibri_context.py
> +        logger.info("Provisioning device…")
As I noted here: https://github.com/learningequality/kolibri/pull/8798#issuecomment-985145131 there is now a mechanism for storing this information in a JSON file and having it be picked up by Kolibri (which will determine whether it is required or not, so will allow the installer here to avoid doing any checks). This should simplify the startup flow and avoid having to do checks.

2021-12-06 23:54 UTC, manuq commented on src/kolibri_gnome/kolibri_context.py
> +        if len(data):
Ah good point. I'm new to type hints but from the documentation using `typing.Any` is like disabling the typing at all, I was trying to prevent that.

2021-12-07 00:02 UTC, manuq commented on src/kolibri_gnome/kolibri_context.py
> +            "facility": {"name": "Kolibri at home"},
Yeah I was expecting a way to pass nothing to the API for the facility name and let Kolibri auto-complete it with the same message used by the setup wizard. See `git grep "SetupStrings.personalFacilityName"` in kolibri code. But it is better to handle the translation here.

2021-12-07 00:04 UTC, manuq commented on src/kolibri_gnome/kolibri_daemon_manager.py
> +                soup_message=soup_message,
I agree, let's refactor the Soup messaging in another task.

2021-12-07 00:06 UTC, manuq commented on src/kolibri_gnome/kolibri_context.py
> +            },
Fantastic! Yes, let's not release this with the dumb admin/admin please.

2021-12-07 00:07 UTC, manuq commented on build-aux/flatpak/modules/0001-Get-port-number-for-zeroconf-from-cherrypy.server.patch
> ++    start_with_ready_cb(port, background, ready_cb=_on_ready)
Thank you Richard. This is still for 0.14 but it's great to know.

2021-12-07 00:12 UTC, manuq commented on src/kolibri_gnome/kolibri_context.py
> +        logger.info("Provisioning device…")
I think we need to provide you context about what are we actually attempting here. The idea is that the flatpak Kolibri app skips all the setup wizard now that we have seamless user management:
- A system admin user is automatically logged into Kolibri as an administrator.
- An unprivileged system user is automatically logged into Kolibri as a learner.

In order to make that work the superadmin user becomes irrelevant, the app language can be automatically set from the system language, and the device provisioning can start in the same way as choosing the quick setup from the wizard.

2021-12-07 01:16 UTC, manuq commented
> I have a few comments, and some things to fix. Also, may you please run `reorder-python-imports src/**/*.py` and `black` on these commits? (Sorry, keep forgetting to add that pre-commit hook here).

Yeah. I would prefer to add the pre-commit now, and format the files with it. I will append that to this PR.

2021-12-07 01:24 UTC, rtibbles commented on src/kolibri_gnome/kolibri_context.py
> +        logger.info("Provisioning device…")
Yes, I understand - my suggestion here is to use supported APIs to do this. All of the data here can be set via a JSON file that gets picked up at Kolibri startup and will automatically provision the device.

As this is for 0.14 still, would not implement this yet - but I followed up here to describe in more detail as @dylanmccall made a PR to Kolibri 0.15 with the changes required for this, so I assumed it was for 0.15.

2021-12-08 02:13 UTC, dylanmccall commented
I'm happy with how this looks now, @manuq. Can you let me know if it's ready to merge? I see there's some fixup commits and I can squash those, but I'm wondering if they're there because you're still working on something :)

2021-12-08 12:03 UTC, manuq commented
> I'm happy with how this looks now, @manuq. Can you let me know if it's ready to merge? I see there's some fixup commits and I can squash those, but I'm wondering if they're there because you're still working on something :)

Yep it is ready to merge. I only left them as fixups so you don't have to review the original commits again :)

I just appended yet another fixup to make the device name translatable, in the same way as the facility name.

2021-12-08 12:12 UTC, manuq commented
> 

@dylanmccall I just rebased on my end. All the fixes were for the  "kolibri-gnome: Automatically provision the device" commit.

2021-12-09 19:22 UTC, merged